apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db-users
  name: db-users
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db-users
  strategy: { }
  template:
    metadata:
      labels:
        io.kompose.service: db-users
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: db
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: password
          image: postgres:alpine
          name: db-users
          ports:
            - containerPort: 5432
          resources: { }
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: db-users
  name: db-users
spec:
  ports:
    - name: jdbc
      port: 5432
      targetPort: 5432
  selector:
    io.kompose.service: db-users