version: '1'

services:
  db-users:
    container_name: db-users
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  microservizi_utenti:
    image: pievit/microservizi_utenti
    stdin_open: true
    tty: true
    build:
      context: .
    container_name: microservizi_utenti
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-users:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"
    depends_on:
      - db-users