version: "3"
services:
  db-users:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
  microservice-users:
    build: .
    image: pievit/microservizi_utenti
    ports:
      - "8080:8080"
    depends_on:
      - db-users